### ISSUE TITLE
clean_taxon_name issue

### ISSUE THREAD

**Issue by haganjam** [haganjam/FW_invert_biomass_allometry#15]
I think there's an issue in this test:

https://github.com/haganjam/FW_invert_biomass_allometry/blob/6b92ec1649cac5c3f6ec723dadf8a068356a831f/tests/testthat/test_clean_taxon_names.R#L69-L76

the "unsup" should be "b" as far as I can tell.

**Comment by black-snow** [comment]
How come? `unsup` is just short for "unsupported" :D (we test that the function errors out if we pass in a life stage that's not supported) @haganjam

**Comment by haganjam** [comment]
The function takes a data.frame and then the third argument specifies the name of the column. So, if we put "unsup" in, then it tests if the function fails if a column name is incorrect. If we but "b" as the third argument, then it actually takes the incorrect life stage names in the make_valid_df()?

**Comment by black-snow** [comment]
Aaaah, now I see - you're right.
