### ISSUE TITLE
Modeling the error in the estimates

### ISSUE THREAD

**Issue by haganjam** [haganjam/FW_invert_biomass_allometry#16]
I think we should model the error in the estimates using the test data that we have. There's not that much but it can be put as an option into the get_trait_from_taxon() function and we can specify that the testing data is not amazing but will be improved in the future. 

I will have a look at compiling the test code properly and seeing what type of model we can fit to the data. We can even go fancy like going for a neural network or something but I would like something that can generate an error distribution around the predicted value.

**Comment by haganjam** [comment]
With the data that you (blacksnow) compiled from Mahrlein et al., we have 850 data points from 70 species which isn't actually too bad. I'm going to give this a crack.

**Comment by black-snow** [comment]
Nice. I might see if there's some more data tageting the *fat worms* :)

**Comment by black-snow** [comment]
Should we associate this with the `1.0.0` milestone? @haganjam
