### ISSUE TITLE
tests for select_traits_tax_dist messed up

### ISSUE THREAD

**Issue by black-snow** [haganjam/FW_invert_biomass_allometry#18]
@haganjam Looks like I broke some tests for `select_traits_tax_dist` when I pulled them apart. Some later tests seem to have depended on `z1`, which is

```r
z1 <- select_traits_tax_dist(data = y1, target_taxon = "taxon_name")
```

in their `mapply` (which looks complicated), e.g.:
```r
    t4 <- mapply(function(spec, all) {
        spec <- spec[, names(spec) != "row_id"]
        all <- all[, names(all) != "row_id"]
        x <- (spec == all)
        all(is.na(x) | (x == TRUE))
    }, z2, z1[c(6, 7)])
    expect_true(all(t4))
```

Can you take a look at it? Can we simplify this? Those tests are hard to grasp. I guess you're testing several things at once there? I think it'd be better to have separate `expect`ations - they'll give distinct errors.

**Comment by black-snow** [comment]
Oh wait, did you already fix it on mainline? I'll rebase and run again.

**Comment by haganjam** [comment]
Yes, I'll take a look.

**Comment by black-snow** [comment]
@haganjam you fixed this already, right?

There was one more issue in `tests/testthat/test_select_traits_tax_dist.R:185` where it said `expect_true(all(t3))` but there was no variable called `t3` - I assumed `x` was correct.

Tests are now all green <3
