### ISSUE TITLE
target_present only defined in one branch

### ISSUE THREAD

**Issue by black-snow** [haganjam/FW_invert_biomass_allometry#24]
There's an issue with new code in `select_traits_tax_dist`: the variable `target_present` only gets [defined](https://github.com/haganjam/FW_invert_biomass_allometry/blob/main/R/select_traits_tax_dist.R#L184) (and set) in one branch (line 173) but apparently that branch doesn't necessarily get hit. [Tests fail](https://github.com/haganjam/FW_invert_biomass_allometry/actions/runs/4864003045/jobs/8672454276?pr=23) in their current state. Or the tests aren't up to date.

It's kinda hard so see what's happening there. `input[["db"]]` should be a col of the input df if I see that right, but there's no such column in the test(s). I can't tell if the code is wrong or the tests :)

We also have a test in `test_get_trait_from_taxon` where the description doesn't seem to match what's actually being tested:

```r
test_that("if all taxon_names are not present in output,
           when get_trait_from_taxon,
           then error", {
```

**Comment by haganjam** [comment]
Indeed. I'm actually busy revising the code for this selection function. Someone I know was using the package and said that it would be nice if we had messages for why a certain taxon name does not have an equation i.e. the body size range doesn't match, the taxon is not present in the taxonomic backbones, the maximum taxonomic distance is too big etc.

I think it's a good idea so I've been working on implementing that but I broke some stuff that now I'm fixing.
