### ISSUE TITLE
usage of undefined variable x.rows

### ISSUE THREAD

**Issue by black-snow** [haganjam/FW_invert_biomass_allometry#9]
https://github.com/haganjam/FW_invert_biomass_allometry/blob/1dffeb74f3a874c7d8954852690c692b2786f3a1/R/clean_taxon_names.R#L149

`x.rows` is undefined there - did we forget it when we did some refactoring?

P. S.: Why's `bdc` creating those nasty `Output` dirs? Super annoying - gonna open an issue there :D

**Comment by haganjam** [comment]
I sorted out the x.rows problem. Yes, we (I) didn't properly commit my changes. Fixed now. Yeah... The Output folder. I just delete it  in a line of code but that's obviously a sub-optimal solution. I'll look into it.

**Comment by black-snow** [comment]
bdc fixed the output thing as well <3 (upcoming 1.1.4, I think)

I'll close this for now.
